### ISSUE TITLE
Keyboard layout remains QWERTY after setting it to Dvorak

### ISSUE THREAD

**Issue by leviport** [wash2/xdg-shell-wrapper#8]
I'm not sure if this one belongs here since it affects both the launcher and the app library, so feel free to move it if this is the wrong place. 

I set my keyboard layout to Dvorak in `.local/state/cosmic-comp/inputs.ron`, but the launcher and the app library are still mapped to QWERTY. All applications are mapped correctly, and the OS hotkeys are mapped the way I expect.

For reference, here is my xkb config in inputs.ron: 
```
    xkb: (
        rules: "",
        model: "",
        layout: "us",
        variant: "dvorak",
        options: Some("altwin:swap_alt_win, caps:ctrl_modifier"),
    ),
```

**Comment by ids1024** [comment]
If other GTK4 applications are working as expected, this would probably be an issue in [`xdg-shell-wrapper`](https://github.com/pop-os/xdg-shell-wrapper). It must not be propagating keymap changes from `wl_keyboard`.

**Comment by ids1024** [comment]
I guess `KeyboardHandler` in `smithay-client-toolkit` should have a method that's called in response to keymap events?

I think otherwise this would need a custom implementation of `Dispatch<wl_keyboard::WlKeyboard, _, _>` instead of just using `delegate_keyboard!`.

**Comment by wash2** [comment]
> For the fields that are not set (“” or None, as set in the Default impl), xkbcommon will use the values from the environment variables XKB_DEFAULT_RULES, XKB_DEFAULT_MODEL, XKB_DEFAULT_LAYOUT, XKB_DEFAULT_VARIANT and XKB_DEFAULT_OPTIONS.
from the smithay docs https://smithay.github.io/smithay/smithay/input/keyboard/struct.XkbConfig.html

Would this be fixed if the above variables were set for panel / applet host? Would that be reasonable for cosmic-session to do?

**Comment by ids1024** [comment]
Env vars presumably aren't a solution here since keymap can be switched dynamically (though this may not be implemented in cosmic-comp yet). Potentially frequently for users of multiple languages/writing systems.

**Comment by ids1024** [comment]
Or actually, when the user switches between multiple layouts they have set, that would generate [`wl_keyboard::modifiers`](https://wayland.app/protocols/wayland#wl_keyboard:event:modifiers) with a different group value, and a new [`wl_keyboard::keymap`](https://wayland.app/protocols/wayland#wl_keyboard:event:keymap) would only be produced when the user changes which layouts are enabled and their order. 

But regardless, xdg-shell-wrapper should propagate keymap changes without having to restart it whenever the keymap settings are changed.

**Comment by ids1024** [comment]
It looks like the current version of `xdg-shell-wrapper` doesn't send `keymap` or `modifiers` to the client at all, so keyboard input isn't working in general.

(I guess that was different with the version of xdg-shell-wrapper based on the older client-toolkit/wayland-rs, as currently used in `cosmic-applet-host`.)

Edit: I tested this using `wev` as a panel applet, and using this `gjs` script:
```js
imports.gi.versions.Gtk = "4.0";
const { GLib, Gtk } = imports.gi;

Gtk.init();

let win = new Gtk.Window();
win.decorated = false;
win.child = new Gtk.Entry();
win.show();

let loop = new GLib.MainLoop(null, false);
loop.run();
```

Edit2: Or is the behavior somewhat inconsistent? Hm.

**Comment by leviport** [comment]
Looks like this is fixed now. My keyboard is Dvorak-ing as expected in both the applibrary and the launcher
